// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using posSystem;

#nullable disable

namespace posSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240704051312_InitialposDB")]
    partial class InitialposDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("posSystem.Models.AdminModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adminCreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminLoginAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminLoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblAdmin");
                });

            modelBuilder.Entity("posSystem.Models.CategoryModel", b =>
                {
                    b.Property<int>("catId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("catId"));

                    b.Property<string>("catCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catCreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catDeleteAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("catUpdateCount")
                        .HasColumnType("int");

                    b.Property<string>("catUpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("catId");

                    b.ToTable("tblCategory");
                });

            modelBuilder.Entity("posSystem.Models.DiscountModel", b =>
                {
                    b.Property<int>("disId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("disId"));

                    b.Property<string>("disCreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disUpdateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("disUpdateCount")
                        .HasColumnType("int");

                    b.HasKey("disId");

                    b.ToTable("tblDiscount");
                });

            modelBuilder.Entity("posSystem.Models.ItemModel", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("itemId"));

                    b.Property<int>("catId")
                        .HasColumnType("int");

                    b.Property<int?>("creatorName")
                        .HasColumnType("int");

                    b.Property<string>("itemBarcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("itemCategory")
                        .HasColumnType("int");

                    b.Property<string>("itemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemCreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("itemRemainStock")
                        .HasColumnType("int");

                    b.Property<int?>("itemSold")
                        .HasColumnType("int");

                    b.Property<int?>("itemStock")
                        .HasColumnType("int");

                    b.Property<int?>("itemSubCategory")
                        .HasColumnType("int");

                    b.Property<string>("itemUpdateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("itemUpdateCount")
                        .HasColumnType("int");

                    b.Property<int>("subCId")
                        .HasColumnType("int");

                    b.HasKey("itemId");

                    b.HasIndex("itemCategory");

                    b.HasIndex("itemSubCategory");

                    b.ToTable("tblItem");
                });

            modelBuilder.Entity("posSystem.Models.LoginDetailModel", b =>
                {
                    b.Property<int>("ldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ldId"));

                    b.Property<int?>("adminId")
                        .HasColumnType("int");

                    b.Property<string>("logOutAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loginAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("staffId")
                        .HasColumnType("int");

                    b.HasKey("ldId");

                    b.ToTable("tblLoginDetail");
                });

            modelBuilder.Entity("posSystem.Models.MemberModel", b =>
                {
                    b.Property<string>("memberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("memberAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberCreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberUpdateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("memberUpdateCount")
                        .HasColumnType("int");

                    b.HasKey("memberId");

                    b.ToTable("tblMember");
                });

            modelBuilder.Entity("posSystem.Models.PromotionModel", b =>
                {
                    b.Property<int>("proId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proId"));

                    b.Property<string>("proCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proCreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proUpdateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("proUpdateCount")
                        .HasColumnType("int");

                    b.HasKey("proId");

                    b.ToTable("tblPromotion");
                });

            modelBuilder.Entity("posSystem.Models.SaleDetailModel", b =>
                {
                    b.Property<int>("sdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sdId"));

                    b.Property<int?>("itemId")
                        .HasColumnType("int");

                    b.Property<int?>("itemPrice")
                        .HasColumnType("int");

                    b.Property<string>("saleDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("saleId")
                        .HasColumnType("int");

                    b.Property<int?>("saleQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("totalAmount")
                        .HasColumnType("int");

                    b.Property<int?>("totalQty")
                        .HasColumnType("int");

                    b.HasKey("sdId");

                    b.HasIndex("itemId");

                    b.HasIndex("saleId");

                    b.ToTable("tblSaleDetail");
                });

            modelBuilder.Entity("posSystem.Models.SaleModel", b =>
                {
                    b.Property<int>("saleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("saleId"));

                    b.Property<string>("discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("paymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("promotion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saleDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("saleQty")
                        .HasColumnType("int");

                    b.Property<string>("staffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("totalAmount")
                        .HasColumnType("int");

                    b.HasKey("saleId");

                    b.HasIndex("memberId");

                    b.HasIndex("staffId");

                    b.ToTable("tblSale");
                });

            modelBuilder.Entity("posSystem.Models.StaffModel", b =>
                {
                    b.Property<string>("staffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("staffAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffCreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffUpdateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("staffUpdateCount")
                        .HasColumnType("int");

                    b.HasKey("staffId");

                    b.ToTable("tblStaff");
                });

            modelBuilder.Entity("posSystem.Models.SubCategoryModel", b =>
                {
                    b.Property<int>("subCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subCId"));

                    b.Property<string>("catCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("catId")
                        .HasColumnType("int");

                    b.Property<string>("subCatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subCatCreateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subCatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subCatUpdateAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("subCatUpdateCount")
                        .HasColumnType("int");

                    b.HasKey("subCId");

                    b.HasIndex("catId");

                    b.ToTable("tblSubCategory");
                });

            modelBuilder.Entity("posSystem.Models.ItemModel", b =>
                {
                    b.HasOne("posSystem.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("itemCategory");

                    b.HasOne("posSystem.Models.SubCategoryModel", "SubCategory")
                        .WithMany()
                        .HasForeignKey("itemSubCategory");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("posSystem.Models.SaleDetailModel", b =>
                {
                    b.HasOne("posSystem.Models.ItemModel", "Item")
                        .WithMany()
                        .HasForeignKey("itemId");

                    b.HasOne("posSystem.Models.SaleModel", "Sale")
                        .WithMany("saleDetails")
                        .HasForeignKey("saleId");

                    b.Navigation("Item");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("posSystem.Models.SaleModel", b =>
                {
                    b.HasOne("posSystem.Models.MemberModel", "Member")
                        .WithMany()
                        .HasForeignKey("memberId");

                    b.HasOne("posSystem.Models.StaffModel", "Staff")
                        .WithMany()
                        .HasForeignKey("staffId");

                    b.Navigation("Member");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("posSystem.Models.SubCategoryModel", b =>
                {
                    b.HasOne("posSystem.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("catId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("posSystem.Models.SaleModel", b =>
                {
                    b.Navigation("saleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
